##########
# collectionbuilder-csv
# Jekyll Digital Collection Generator
# https://github.com/CollectionBuilder/collectionbuilder-csv
##########

##########
# URL VARIABLES
#
# site domain, full URL to the production location of your collection
url: 
# path to location on the domain if necessary e.g. /digital/hjccc
baseurl: 
# location of code, the full url to your github repository
source-code: https://github.com/CollectionBuilder/collectionbuilder-csv

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Gameophiles Unlimited
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: A collection of jigsaw puzzles and boardgames from a New Jersey-based manufacturer that was active in the early to mid-1970s
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: |
  **Gameophiles Unlimited** was based in Morristown and Berkeley Heights, New Jersey, in the early to mid-1970s before being acquired by Nordevco.  

  Despite its brief existence, Gameophiles Unlimited produced a diverse range of innovative jigsaw puzzles and board games. Their puzzles featured unique designs, including a *1040 tax form puzzle*, an *empty calendar* that could be customized with a felt marker, and *maps of subways and roads*.  

  They also released a series of *100-piece Pic-Me-Up puzzles*, showcasing illustrations by *Beatrix Potter* and *Wallace Tripp*.  

  Their board game collection was equally distinctive, featuring titles such as *Pentagon: A Marble Game* and *The Front Page*, which challenged players to compete in assembling the best layout for the *Main Street Herald* newspaper. *The Chicagoan Game* even encouraged players to "steal" from the bank, adding a playful twist to traditional gameplay.  

  This digital exhibit has been created to **archive and document** Gameophiles Unlimited's products, as well as ephemera associated with the company, preserving its legacy in the world of puzzles and board games.

# keywords, a short list of subjects describing the collection, separated by semicolon, to appear in rich markup
keywords: gameophiles unlimited; jigsaw puzzles; boardgames; 1970s
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Zuzanna Kelvin

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the CSV file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: gameophiles-puzzles-metadata
# page generation settings [optional!]
# [optional: only used if you need to tweak CB defaults or generate from more than one data file]
# page_gen:
#   - data: 'demo-metadata'
#     template: 'item'
#     name: 'objectid'
#     dir: 'items'
#     extension: 'html' 
#     filter: 'objectid'  

##########
# Site/Organization Branding 
#   Enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#   To remove the branding, comment out these values, or delete them. 
#
organization-name:
organization-link: 
organization-logo-banner:
organization-logo-nav:

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, rakelib/, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md, SECURITY.md]
# compress CSS output
sass:
  style: compressed
